version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "23:30"
  open-pull-requests-limit: 99
  reviewers:
  - varunsridharan
  assignees:
  - varunsridharan
  ignore:
  - dependency-name: wponion/wponion
    versions:
    - 1.5.3.2
    - 1.5.3.3
    - 1.5.3.4
    - 1.5.3.5
    - 1.5.3.6
  - dependency-name: varunsridharan/wpallimport_rapidaddon
    versions:
    - "262498148"
