name: On Push

on:
  push:
    branches:
      - master

jobs:
  PHP_Docs_ApiGen:
    runs-on: ubuntu-latest
    steps:
      - name: Fetching Repository
        uses: actions/checkout@v1
      - name: Generating PHP Documentation
        uses: varunsridharan/action-apigen@1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
